// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARrDzldmar42zrvJp84ZKxayjfiz7uiQY',
    appId: '1:555001702609:web:970320b916d4301e773df0',
    messagingSenderId: '555001702609',
    projectId: 'reviewer-62a93',
    authDomain: 'reviewer-62a93.firebaseapp.com',
    storageBucket: 'reviewer-62a93.firebasestorage.app',
    measurementId: 'G-6P9C4995RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCGEx0tLcLgFT4V4dfFZWTnF-wP9ue5N8',
    appId: '1:555001702609:android:ccb84ba958a764a0773df0',
    messagingSenderId: '555001702609',
    projectId: 'reviewer-62a93',
    storageBucket: 'reviewer-62a93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYYwpt0-bPvJU-DppgsTAz0mr5V9De8sU',
    appId: '1:555001702609:ios:a7ace5ea60fd5b30773df0',
    messagingSenderId: '555001702609',
    projectId: 'reviewer-62a93',
    storageBucket: 'reviewer-62a93.firebasestorage.app',
    iosBundleId: 'com.example.reviewerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYYwpt0-bPvJU-DppgsTAz0mr5V9De8sU',
    appId: '1:555001702609:ios:a7ace5ea60fd5b30773df0',
    messagingSenderId: '555001702609',
    projectId: 'reviewer-62a93',
    storageBucket: 'reviewer-62a93.firebasestorage.app',
    iosBundleId: 'com.example.reviewerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARrDzldmar42zrvJp84ZKxayjfiz7uiQY',
    appId: '1:555001702609:web:5b1a8a4cfd7b8b3d773df0',
    messagingSenderId: '555001702609',
    projectId: 'reviewer-62a93',
    authDomain: 'reviewer-62a93.firebaseapp.com',
    storageBucket: 'reviewer-62a93.firebasestorage.app',
    measurementId: 'G-X8MYVYLLYJ',
  );
}
